// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoreCardPlus;

#nullable disable

namespace ScoreCardPlus.Migrations
{
    [DbContext(typeof(ScoreCardDBContext))]
    [Migration("20230801022722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("ScoreCardPlus.Models.ScoreCard", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Course")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberofHoles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberofPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParCourseTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("ScoreCards");
                });
#pragma warning restore 612, 618
        }
    }
}
